### ISSUE TITLE
Range input thumb blocks mouse input

### ISSUE THREAD

**Issue by skattyadz** [mderrick/react-html5video#108]
If you click somewhere on the volume slider that's near the existing value nothing happens. This is because you're actually clicking on the draggable 'thumb'

Adding this solves the problem in Chrome:

```css
      input[type='range']::-webkit-slider-thumb {
        pointer-events: none;
      }
```

Could be an easy PR for a beginner
